---
  app:
    version: 1.5
    env: staging

  fav:
    color: black
    fruit: orange

  dbconn:
    host: 127.0.0.1
    user: devop
    pass: redhat5111
    db: devopsdemo

#  haproxy_backend_httpchk: ''
#  haproxy_socket: /var/run/haproxy.sock


  mysql_root_password: linux5111
  mysql_databases:
    - name: devopsdemo
      encoding: latin1
      collation: latin1_general_ci
  mysql_users:
    - name: devop
      host: "%"
      password: redhat5111
      priv: "devopsdemo.*:ALL"
  mysql_bind_address: '0.0.0.0'

