---
  users:
    admin:
      uid: 5005
      shell: /bin/bash
      home: /home/admin
      state: present
 #   dojo:
  #    state: absent

  systems:
    packages:
      - ntp
      - tree
      - vim

